// label為array，label[0]甜鹹，label[1]區域

const article = [
  {
    id: 1,
    title: "歡迎來到白色戀人公園",
    titleInTrans: "",
    snackName: "白色戀人",
    snackNameOrigin: "白い恋人パーク",
    summary:
      "公司創始人石水幸安滑雪回來，沒有什麼特別理由地感慨了一句「白色的戀人們紛紛降下來了呢」，於是便成了品牌的名字。",
    updaingDate: "July 2021",
    nation: "日本",
    nationICon: "",
    label: ["甜食", "亞洲"],
    resource: "https://www.shiroikoibitopark.jp/",
    image1: "/images/article_story/1/1_1.jpg",
    image2: "/images/article_story/1/1_2.jpg",
    image3: "/images/article_story/1/1_3.jpg",
    image4: "/images/article_story/1/1_4.jpg",
    image5: "/images/article_story/1/1_5.jpg",
    image6: "/images/article_story/1/1_6.jpg",

    content:
      "70年代白色巧克力正當紅，石屋制果股份公司（石屋製菓株式會社）傷透腦筋想辦法開發出既能吃到白色巧克力，又可以不會沾到手的產品。最後得到的結論是用餅乾薄片夾住巧克力，白色戀人也就誕生了。由來是：公司創始人石水幸安滑雪回來，沒有什麼特別理由地感慨了一句「白色的戀人們紛紛降下來了呢」，於是便成了品牌的名字。",
  },
  {
    id: 2,
    title: "阿美利卡.ICON",
    titleInTrans: "How Oreos Got Their Name: The Rise of an American Icon",
    snackName: "OREO",
    snackNameOrigin: "Oreo",
    summary: "Oreo，如何成為美國ICON?!",
    updaingDate: "June, 2021",
    nation: "美國",
    nationICon: "",
    label: ["甜食", "美洲"],
    resource: "https://www.oreo.com/pokemon",
    image: "",
    content:
      "OREO因業績慘澹推出牛奶夾心餅乾 意外打敗原創Hydrox。1912年億滋國際（Mondelēz International）旗下的餅乾品牌納貝斯克（Naisco）創造出的產品，其實是抄襲1908年的「Hydrox」餅乾。起初只是OREO「借鏡」Hydrox餅乾上的花紋，兩者口味大不相同，OREO原先主打檸檬口味而Hydrox販售巧克力與奶油。但由於OREO業績慘澹，決定製作出中間夾奶油的OREO，也就是現在市面上販售的口味。此一舉動也讓Hydrox提告OREO。但由於圓形是基本形狀，牛奶夾心餅乾是基本加工兩項不能申請專利，所以沒有法律能制裁OREO。由於OREO推出牛奶的夾心餅乾大獲好評，銷量也勝過原創者Hydrox，直到1999年Hydrox宣布停產，直到2014年Hydrox被Leaf收購後重出江湖。",
  },
  {
    id: 3,
    title: "義大利的國民零食",
    titleInTrans: "kinder you day",
    snackName: "健達繽紛樂",
    snackNameOrigin: "Kinder Bueno",
    summary: "你今天「繽紛樂」了沒？",
    updaingDate: "May 2021",
    nation: "義大利",
    nationICon: "",
    label: ["甜食", "歐洲"],
    resource: "https://en.wikipedia.org/wiki/Kinder_Bueno",
    image: "",
    content:
      "「健達繽紛樂」算是台灣家喻戶曉的巧克力條。當大人努力制止小朋友不過分沈溺於「Kinder Bueno」與其甜膩的口感，或許，尚未意識到這毫不起眼的巧克力棒實為是歐洲人的國民小食。其看似新營的外表其實可以追溯至1978年的義大利，直到1991年才改至德國生產。",
  },
  {
    id: 4,
    title: "蓮花餅 x 咖啡新配方",
    titleInTrans: "The Lotus Biscoff Latte Recipe",
    snackName: "蓮花餅",
    snackNameOrigin: "Lotus Biscoff",
    summary:
      "左手剛舉起一杯熱咖啡，小湊一口咖啡因的刺激，不僅想要來一塊蓮花餅（lotus biscoff）",
    updaingDate: "Aug 2022",
    nation: "比利史",
    nationICon: "",
    label: ["甜食", "歐洲"],
    resource: "https://www.lotusbiscoff.com/en-us",
    image: "",
    content:
      "在台灣，大家必會有一印象，左手剛舉起一杯熱咖啡，小湊一口咖啡因的刺激，不僅想要來一塊蓮花餅（lotus biscoff），入口即化的口感成為安撫咖啡因刺激最後的慰藉。在1932年，一位比利時籍的麵包師傅Jan Boone S，首度創造出這一種焦糖化的餅乾，他以蓮花為名自許餅乾如此純粹，造福許多不甘於咖啡因之人。",
  },
  {
    id: 5,
    title: "素食愛好者之雜糧餅乾",
    titleInTrans: "The Best Vegan Cookie Brands To Buy ",
    snackName: "雜糧餅乾",
    snackNameOrigin: "vegan cookies",
    summary:
      "Are vegan cookies healthy？And, How to pick the best vegan cookies.",
    updaingDate: "Aug 2022",
    nation: "Cross Continent",
    nationICon: "",
    label: ["甜食", "歐洲"],
    label: ["", ""],
    resource: "https://www.eatthis.com/best-vegan-cookies/",
    image: "",
    content:
      "If you've ever wondered if vegan cookies are better for you than their non-vegan counterparts, there are some important things to keep in mind.",
  },
  {
    id: 6,
    title: "匈牙利必買的特色零食",
    titleInTrans: "",
    snackName: "Multiple",
    snackNameOrigin: "Multiple",
    summary:
      "到了匈牙利只買了必買的貴腐酒和鵝肝醬嗎？愛吃零食的你是不是還想試試匈牙利口味的零食啊～這裡幫大家介紹了五款匈牙利特色零食，款款都是精挑細選，不容錯過的特色款式哦！",
    updaingDate: "Aug 2022",
    nation: "匈牙利",
    nationICon: "",
    label: ["甜食", "歐洲"],
    resource: "https://snacklips.com/hungarymusteat-blog/",
    image: "",
    content:
      "google煙囪捲多會出現捷克傳統點心，實際上同處於東歐位置的匈牙利布達佩斯一樣滿街都是煙囪捲！雪華姐耳提面命必吃的煙囪捲名店，是我們抵達Budapest的第1餐，有了非常好的第一印象，大推杏仁口味的煙囪捲呀，有焦香脆口感的杏仁片真是銷魂。",
  },
  {
    id: 7,
    title: "原來法國除了馬卡龍還有…",
    titleInTrans: "原來法國除了馬卡龍還有…",
    snackName: "Multiple",
    snackNameOrigin: "Multiple",
    summary:
      "甜點在法國生活，佔據很重要的地位；有如傳統華人飲食文化的飯後水果...",
    updaingDate: "Aug 2022",
    nation: "法國",
    nationICon: "",
    label: ["甜食", "歐洲"],
    resource: "https://snacklips.com/8musteatfrenchsnack-blog/",
    image: "",
    content:
      "甜點在法國生活，佔據很重要的地位；有如傳統華人飲食文化的飯後水果 🍎 對於法國人來說，倘若沒有飯後甜點，這頓飯就不完整，即便是巧克力都可。在法國文化中，如果收到法國人的邀請，到家中聚餐，大家可以帶上甜點、一瓶紅酒或是一束花。",
  },
  {
    id: 8,
    title: "德國特寫：方正裡的好滋味",
    titleInTrans: "德國特寫：方正裡的好滋味",
    snackName: "Multiple",
    snackNameOrigin: "Multiple",
    summary:
      "我們聽過德國車、德國人、德國機械的工藝，那是否聽過德國的零食？！這一切就從方正的外包裝說起吧...",
    updaingDate: "Aug 2022",
    nation: "德國",
    nationICon: "",
    label: ["甜食", "歐洲"],
    resource: "https://snacklips.com/germany12musteat-blog/",
    image: "",
    content:
      "如果你在聖誕節期間曾經去過德國或其他講德語的國家，那麼你已經知道德國餅乾和甜點的美味了，但其中許多都沉浸在具有幾個世紀歷史的傳統中。巴塞爾巧克力球：用巧克力，杏仁和榛子製成的甜蜜糖果; 聖誕節款待。",
  },
  {
    id: 9,
    title: "走出二戰悲痛：波蘭經典零食",
    titleInTrans: "走出二戰悲痛：波蘭經典零食",
    snackName: "Multiple",
    snackNameOrigin: "Multiple",
    summary:
      "最近愈來愈多人喜歡去神秘感較濃厚的東歐玩，今天要來跟大家介紹位於東歐的波蘭旅遊必吃...",
    updaingDate: "Aug 2022",
    nation: "波蘭",
    nationICon: "",
    label: ["鹹食", "歐洲"],
    resource: "https://snacklips.com/polishbest8snacks-blog/",
    image: "",
    content:
      "最近愈來愈多人喜歡去神秘感較濃厚的東歐玩，今天要來跟大家介紹位於東歐的波蘭旅遊必吃，這些都是 超市就能買的到 的平價零嘴喔！波蘭的糖果餅乾巧克力普遍來說口味偏重偏甜，所以相當適合來杯茶搭配享用～馬上來看看波蘭人推薦的八大必吃經典吧：",
  },
  {
    id: 10,
    title: "洋芋片的誕生：以英國為例",
    titleInTrans: "洋芋片的誕生：以英國為例",
    snackName: "Multiple",
    snackNameOrigin: "Multiple",
    summary:
      "洋芋片是一位廚師為了對付奧客而誕生的嗎？廚師對客人的復仇，刻意把馬鈴薯條切成極薄的片狀，炸得酥脆、讓客人無法用叉子食用...",
    updaingDate: "Aug 2021",
    nation: "英國",
    nationICon: "",
    label: ["鹹食", "歐洲"],
    resource: "https://snacklips.com/potatochips-snacks-blog/",
    image: "",
    content:
      "一位廚師因為客人嫌棄做的薯條太厚了！拒絕付帳，於是廚師憤慨之下把馬鈴薯條切成極薄的片狀，炸得酥脆、讓客人無法用叉子將他插起，他想這樣不方便食用便可報復這位客人，沒想到客人非常喜愛之外，也成為了店裡的一道正式料理，深受大眾喜愛，並且成為了改寫歷史還有沙發的好朋友的偉大零食！",
  },
  {
    id: 11,
    title: "",
    titleInTrans: "",
    snackName: "",
    snackNameOrigin: "",
    summary: "",
    updaingDate: "",
    nation: "",
    nationICon: "",
    label: ["", ""],
    resource: "",
    image: "",
    content: "",
  },
];
